### PR TITLE
Fix execution cancellation

### LINKED ISSUE #353: Excecution cancellation doesn't work
**Describe the bug**
Clicking "cancel" on the indicator during texts excecutions doesn't work.

**To Reproduce**
1. Generate tests
2. Click "Run all"
3. Cancel in the bottom

### PR DESCRIPTION
**Pull request by arksap2002**
# Description of changes made
Fix "run all" button cancellation. Checks for indicator cancellation and returns states of all remaings test cases.

# Other notes
Closes #353 

- [x] I have checked that I am merging into correct branch

### CODE REVIEW

**Review by pderakhshanfar — APPROVED** [review]

File: src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TopButtonsPanelBuilder.kt [hunk 1]
```diff
@@ -107,21 +107,33 @@ class TopButtonsPanelBuilder {
             testCasePanelFactory.addTask(tasks)
         }
         // run tasks one after each other
-        executeTasks(project, tasks)
+        executeTasks(project, tasks, runAllButton, generatedTestsTabData)
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TopButtonsPanelBuilder.kt:110]: You do not need to provide `runAllButton` into `executeTasks`, as this button is already a member field of the current class:
```kotlin
class TopButtonsPanelBuilder {
    private var runAllButton: JButton = createRunAllTestButton()
```

File: src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TopButtonsPanelBuilder.kt [hunk 2]
```diff
@@ -107,21 +107,33 @@ class TopButtonsPanelBuilder {
...
 
                 override fun onFinished() {
                     super.onFinished()
-                    executeTasks(project, tasks)
+                    if (globalIndicator != null && !globalIndicator!!.isCanceled) {
+                        executeTasks(project, tasks, runAllButton, generatedTestsTabData)
+                    } else {
+                        if (tasks.isNotEmpty()) {
+                            runAllButton.isEnabled = true
+                            for (index in generatedTestsTabData.testCasePanelFactories.size - tasks.size - 1 until generatedTestsTabData.testCasePanelFactories.size) {
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TopButtonsPanelBuilder.kt:132]: This range is hard to understand. I suggest moving both start and end indices into a named variable so that it becomes easier to read:
```kotlin
generatedTestsTabData.testCasePanelFactories.size - tasks.size - 1 until generatedTestsTabData.testCasePanelFactories.size
```

**Review by Vladislav0Art — CHANGES_REQUESTED** [review]
We need to start thinking about a [transition to Kotlin coroutines](https://github.com/JetBrains-Research/TestSpark/issues/257). Although this `ProgressManager`-related API is marked obsolete, we still use it. 

Besides, in this particular case, we could efficiently parallelize the execution of test cases if we used coroutines. Currently, we execute test cases iteratively one by one which is very slow in comparison.

Additionally, it becomes hard to manage cancellations, progress-based executions, and state updates as the project grows.

CC: @arksap2002 @pderakhshanfar @Hello-zoka

**Comment by Vladislav0Art** [comment]
Rebased on `development`.
