### PR TITLE
Fix imports saving

### LINKED ISSUE #176: Imports of the final test suite are incomplete
**Describe the bug**
Among N iterations of the feedback cycle TestSpark collects all of the test cases that were compilable on every iteration but the resulting test suite will contain only the imports that were provided by the LLM on the **last iteration**: 

**To Reproduce**
Steps to reproduce the behavior (it is easier to reproduce on the headless mode):
1. Select a complex project under test.
2. Start LLM test generation and retry until the LLM generates 2 test suites on different iterations with different sets of imports.
3. The final test suite may contain the test cases from the both generation test suites on the step 2. by some imports may be missing.

**Expected behavior**
We need to collect a union of the imports in the final test suite. It is okay to have redundant imports but it is not okay to have duplicated or missing imports.

**Additional context**

See the following LLM responses during the feedback cycle. There 2 test suites `DBAppTest` generated, both with some compilable test cases but the resulting test suite has missing imports (see after below): 

```log
``java
package test;

import app.DBApp;
import exceptions.DBAppException;
import org.junit.Assert;
import org.junit.Test;
import java.io.IOException;
import java.util.Hashtable;

public class DBAppTest {
    
    @Test
    public void getMyTablesTest() {
        DBApp dbApp = new DBApp();
        Assert.assertNotNull(dbApp.getMyTables());
    }

    @Test
    public void initTest() {
        DBApp dbApp = new DBApp();
        dbApp.init();
        // If function runs successfully we can assert the the size of tables is not zero
        Assert.assertNotEquals(0, dbApp.getMyTables().size());
    }

    @Test(expected = DBAppException.class)
    public void createTableTest() throws DBAppException, IOException {
        DBApp dbApp = new DBApp();
        Hashtable<String, String> htblColNameType = new Hashtable<>();
        htblColNameType.put("id", "java.lang.Integer");
        htblColNameType.put("name", "java.lang.String");
        
        Hashtable<String, String> htblColNameMin = new Hashtable<>();
        htblColNameMin.put("name", "AAAAA");
        
        Hashtable<String, String> htblColNameMax = new Hashtable<>();
        htblColNameMax.put("name", "zzzzz");
        
        dbApp.createTable("staff", "id", htblColNameType, htblColNameMin, htblColNameMax); 
    }

    @Test(expected = DBAppException.class)
    public void insertIntoTableInvalidNameTest() throws DBAppException {
        DBApp dbApp = new DBApp();
        Hashtable<String, Object> htblColNameValue = new Hashtable<>();
        htblColNameValue.put("id", 1);
        htblColNameValue.put("name", "John");
        
        dbApp.insertIntoTable("student", htblColNameValue);
    }


    @Test(expected = DBAppException.class)
    public void insertIntoTableCorrectNameTest() throws DBAppException {
        DBApp dbApp = new DBApp();
        Hashtable<String, Object> htblColNameValue = new Hashtable<>();
        htblColNameValue.put("id", 1);
        htblColNameValue.put("name", "John");
        
        dbApp.insertIntoTable("staff", htblColNameValue);
    }

    @Test(expected = DBAppException.class)
    public void updateTableInvalidNameTest() throws DBAppException {
        DBApp dbApp = new DBApp();
        Hashtable<String, Object> htblColNameValue = new Hashtable<>();
        htblColNameValue.put("name", "Mike");
        
        dbApp.updateTable("student", "1", htblColNameValue);
    }
    
    @Test(expected = DBAppException.class)
    public void deleteFromTableInvalidNameTest() throws DBAppException {
        DBApp dbApp = new DBApp();
        Hashtable<String, Object> htblColNameValue = new Hashtable<>();
        htblColNameValue.put("name", "Mike");
        
        dbApp.deleteFromTable("student", htblColNameValue); 
    }

    @Test(expected = DBAppException.class)
    public void selectFromTableInvalidNameTest() throws DBAppException {
        DBApp dbApp = new DBApp();
        String[] strarrOperators = {"<"};
        dbApp.selectFromTable(new SQLTerm[]{}, strarrOperators); 
    }

    @Test(expected = DBAppException.class)
    public void selectFromTableCorrectNameTest() throws DBAppException {
        DBApp dbApp = new DBApp();
        String[] strarrOperators = {"<"};
        SQLTerm[] arrSQLTerms = new SQLTerm[1];
        arrSQLTerms[0] = new SQLTerm();
        arrSQLTerms[0].strTableName = "staff";
        arrSQLTerms[0].strColumnName = "id";
        arrSQLTerms[0].strOperator = "<";
        arrSQLTerms[0].objValue = "500";
        
        dbApp.selectFromTable(arrSQLTerms, strarrOperators);
    }
}
``
================================================================================
I'm sorry for the confusion. If the SQLTerm class is not visible or accessible, we need to adapt the testing approach. Unfortunately, without having the respective SQLTerm class (we only have its named reference in the DBApp class), it's not possible to construct its objects to use in selectFromTable tests. It seems like SQLTerm is a part of the project but not part of app package. 

The creation and usage of the SQLTerm instances in test cases for the 'selectFromTable' method could be adjusted according to real structure, fields and accessibility of the SQLTerm class which is not present within the details provided for the scenario. 

However, I can show you how you can detect that SQLTerm class is imported correctly. I'll use placeholders for that. These placeholders should be replaced by real SQLTerm invocations:

``java
import placeholderPackage.SQLTerm; // Correct import statement for SQLTerm

@Test(expected = DBAppException.class)
public void selectFromTableInvalidNameTest() throws DBAppException {
    DBApp dbApp = new DBApp();
    String[] strarrOperators = {"<"};
    SQLTerm term = buildSQLTerm(); // Helper method that creates SQLTerm instance
    dbApp.selectFromTable(new SQLTerm[]{term}, strarrOperators); 
}

protected SQLTerm buildSQLTerm() {
    SQLTerm term = new SQLTerm();
    // Add all necessary attribute assignments to correctly construct SQLTerm instance. 
    // This depends on SQLTerm class definition which isn't provided in the prompt.
    return term;
}
``
In above code, you need to replace 'placeholderPackage' with a real package where SQLTerm exists and you need to implement 'buildSQLTerm' method according to 'SQLTerm' construction requirements.

For the accurate tests, I would need more information about the `SQLTerm` class, how it's structured and how it's used in normal operation of the database application you're testing. This includes information about its constructors and methods, as well as the expected results of those methods in normal use. This kind of information is essential to write accurate and effective tests.
=================================================================================
My apologies for the misunderstanding. Below is the fixed version:

``java
import placeholderPackage.SQLTerm; // Correct import statement for SQLTerm
import java.lang.DBAppException;

@Test(expected = DBAppException.class)
public void selectFromTableInvalidNameTest() throws DBAppException {
    DBApp dbApp = new DBApp();
    String[] strarrOperators = {"<"};
    SQLTerm term = buildSQLTerm(); // Helper method that creates SQLTerm instance
    dbApp.selectFromTable(new SQLTerm[]{term}, strarrOperators); 
}

protected SQLTerm buildSQLTerm() {
    SQLTerm term = new SQLTerm();
    // Add all necessary attribute assignments to correctly construct SQLTerm instance. 
    // This depends on SQLTerm class definition which isn't provided in the prompt.
    return term;
}
``
In the import statements at the top of the script, replace `placeholderPackage` with the actual package where your `SQLTerm` class is located.

In the `buildSQLTerm` function, you should replace the comments section with code to populate your `SQLTerm` instance using the appropriate attributes and methods from that class. Unfortunately, as I don't have the specific details of the `SQLTerm` class, I am unable to provide specifics for this part.
===================================================================================
My sincere apologies for the errors in the previous example, and thank you for your patience. Please see the corrected version below.

``java
import app.DBApp;
import exceptions.DBAppException;
import org.junit.Test;
import java.util.Hashtable;
//make sure to import SQLTerm, since the correct import statement is not given, placeholder is used
import placeholderPackage.SQLTerm;

public class DBAppTest {
    
    // other test methods ....
    
    @Test(expected = DBAppException.class)
    public void selectFromTableInvalidNameTest() throws DBAppException {
        DBApp dbApp = new DBApp();
        String[] strarrOperators = {"<"};
        SQLTerm term = buildSQLTerm();
        dbApp.selectFromTable(new SQLTerm[]{term}, strarrOperators); 
    }

    private SQLTerm buildSQLTerm() {
        // Assuming example creation of SQLTerm
        SQLTerm term = new SQLTerm(); // Replace this line with the correct initialization of SQLTerm.
        // term.setStrTableName("staff");  // example setters
        // term.setStrColumnName ("id");  // based on SQLTerm class
        // term.setStrOperator ("<");
        // term.setObjValue ("500");   
        return term;
    }
}
``

In the code above, the `"placeholderPackage"` import is a placeholder for the actual import statement for SQLTerm class.

The `buildSQLTerm()` method is a helper method that returns an instance of SQLTerm. The implementation of this method would depend on the constructor(s) or setter methods available in the SQLTerm class, which is not provided in the class under test or the prompt. Replace it with your actual SQLTerm construction logic.
=========================================================================================
```

The final collected test with the missing imports:

```java
package app;

import app.DBApp;
import exceptions.DBAppException;
import org.junit.Test;

import java.util.Hashtable;

import placeholderPackage.SQLTerm;

public class GeneratedTest {


    // other test methods ....

    @Test
    public void getMyTablesTest() {
        DBApp dbApp = new DBApp();
        Assert.assertNotNull(dbApp.getMyTables());
    }

    @Test
    public void initTest() {
        DBApp dbApp = new DBApp();
        dbApp.init();
        // If function runs successfully we can assert the the size of tables is not zero
        Assert.assertNotEquals(0, dbApp.getMyTables().size());
    }

    @Test
    public void createTableTest() throws DBAppException, IOException {
        DBApp dbApp = new DBApp();
        Hashtable<String, String> htblColNameType = new Hashtable<>();
        htblColNameType.put("id", "java.lang.Integer");
        htblColNameType.put("name", "java.lang.String");

        Hashtable<String, String> htblColNameMin = new Hashtable<>();
        htblColNameMin.put("name", "AAAAA");

        Hashtable<String, String> htblColNameMax = new Hashtable<>();
        htblColNameMax.put("name", "zzzzz");

        dbApp.createTable("staff", "id", htblColNameType, htblColNameMin, htblColNameMax);
    }

    @Test
    public void insertIntoTableInvalidNameTest() throws DBAppException {
        DBApp dbApp = new DBApp();
        Hashtable<String, Object> htblColNameValue = new Hashtable<>();
        htblColNameValue.put("id", 1);
        htblColNameValue.put("name", "John");

        dbApp.insertIntoTable("student", htblColNameValue);
    }

    @Test
    public void insertIntoTableCorrectNameTest() throws DBAppException {
        DBApp dbApp = new DBApp();
        Hashtable<String, Object> htblColNameValue = new Hashtable<>();
        htblColNameValue.put("id", 1);
        htblColNameValue.put("name", "John");

        dbApp.insertIntoTable("staff", htblColNameValue);
    }

    @Test
    public void updateTableInvalidNameTest() throws DBAppException {
        DBApp dbApp = new DBApp();
        Hashtable<String, Object> htblColNameValue = new Hashtable<>();
        htblColNameValue.put("name", "Mike");

        dbApp.updateTable("student", "1", htblColNameValue);
    }

    @Test
    public void deleteFromTableInvalidNameTest() throws DBAppException {
        DBApp dbApp = new DBApp();
        Hashtable<String, Object> htblColNameValue = new Hashtable<>();
        htblColNameValue.put("name", "Mike");

        dbApp.deleteFromTable("student", htblColNameValue);
    }

}
```

The compilation error of the test suite is the following, although the compilation of each individual test cases was successful:

```log
'/home/ubuntu/projects/tga-pipeline/artifacts/generation-2/augmented-prompt-full/TestSpark/0/database-engine-8314bfdec0/app/GeneratedTest.java:9: error: package placeholderPackage does not existimport placeholderPackage.SQLTerm;                         ^/home/ubuntu/projects/tga-pipeline/artifacts/generation-2/augmented-prompt-full/TestSpark/0/database-engine-8314bfdec0/app/GeneratedTest.java:31: error: cannot find symbol    public void createTableTest() throws DBAppException, IOException {                                                         ^  symbol:   class IOException  location: class GeneratedTest/home/ubuntu/projects/tga-pipeline/artifacts/generation-2/augmented-prompt-full/TestSpark/0/database-engine-8314bfdec0/app/GeneratedTest.java:19: error: cannot find symbol        Assert.assertNotNull(dbApp.getMyTables());        ^  symbol:   variable Assert  location: class GeneratedTest/home/ubuntu/projects/tga-pipeline/artifacts/generation-2/augmented-prompt-full/TestSpark/0/database-engine-8314bfdec0/app/GeneratedTest.java:27: error: cannot find symbol        Assert.assertNotEquals(0, dbApp.getMyTables().size());        ^  symbol:   variable Assert  location: class GeneratedTest4 errors'
Compiled class not found at '/home/ubuntu/projects/tga-pipeline/artifacts/generation-2/augmented-prompt-full/TestSpark/0/database-engine-8314bfdec0/app/GeneratedTest.class'
```

### PR DESCRIPTION
**Pull request by arksap2002**
# Description of changes made
Save imports from all iterations of the LLM feedback cycle

# Other notes
Closes #176 

- [x] I have checked that I am merging into correct branch

### CODE REVIEW

File: core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/LLMWithFeedbackCycle.kt [hunk 1]
```diff
@@ -80,6 +80,9 @@ class LLMWithFeedbackCycle(
         var executionResult = FeedbackCycleExecutionResult.OK
         val compilableTestCases: MutableSet<TestCaseGeneratedByLLM> = mutableSetOf()
 
+        // collect imports from all responses
+        val imports: MutableList<String> = mutableListOf()
```
Comment (Vladislav0Art) [inline core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/LLMWithFeedbackCycle.kt:84]: **nitpick:** We can make it `MutableSet<String>` so that duplicates are removed as we go. The current implementation is also correct, but a set, in my opinion, fits better ideologically.

**Review by Vladislav0Art — APPROVED** [review]
All good! 🌟

**Review by pderakhshanfar — APPROVED** [review]
