### PR TITLE
Java path for kotlin tests compilation on Windows machines

### LINKED ISSUE #320: Add error message if `javac` or `kotlinc` are not found
**Describe the bug**
In a situation where there is no compiler, the plugin does not show an error.

### LINKED ISSUE #410: `kotlinc` requires `javac` on Windows
**Describe the bug**
Windows' `kotlinc` calls `javac` (**_or `java`?_**) in its internals. If there is no `javac` in `PATH` the compilation fails. In `KotlinTestCompiler` we need to search for both `kotlinc` and `javac`, and somehow let `kotlinc` "know" about `javac`.

**To Reproduce**
1. Run test generation on Windows (ensure no `javac` is present in PATH; it should be the case it you did not install `java` manually, from Oracle, for example).
2. Observe compilation errors; see the console output; there should be an error about `javac` not found. 

**Expected behavior**
Kotlin compilation should work correctly on Windows.

**Additional context**
Another Windows issue is this one: #407. These two issues are different, yet both relate to Windows compilation.

### PR DESCRIPTION
**Pull request by SergeyDatskiv**
In this merge request we are closing an issue where Windows users who did not have java in their PATH variable could not run the generated kotlin tests because `kotlinc` requires Java to be in the path variable.

# Description of changes made
To address this issue, I added the same Java Path, which is used by the `JavaTestCompiler` to the `KotlinTestCompiler` class. This required changing the `TestCompilerFacotry` to find the Java path and pass it to `KotlinTestCompiler`. I decided to remove dedicated functions for creating Kotlin and Java test compilers because I thought that now they are more similar than different. Instead, I added a private function for finding the Java home path. 

The `KotlinTestCompiler` now gets a `javaHomeDirectoryPath` which is not directly assigned in the constructor because that would require changing the `TestCompiler` class. I thought that `TestCompiler` class should not be dedicated to the Java / Kotlin language, hence I did not change it. 

The Java path is set only if we detect that the system is a Windows machine. It is set through a chain of commands via command prompt.

# Other notes
- [x] Please test that nothing broke on Mac with regard to Java- and Kotlin-based test case generation. Thanks!

# Why is merge request needed
Closes #410
Closes #320 

- [X] I have checked that I am merging into correct branch

### CODE REVIEW

File: src/main/kotlin/org/jetbrains/research/testspark/tools/factories/TestCompilerFactory.kt [hunk 1]
```diff
@@ -24,33 +24,41 @@ object TestCompilerFactory {
...
         }
-
-        return JavaTestCompiler(libraryPaths, junitLibraryPaths, javaSDKHomePath)
-    }
-
-    private fun createKotlinCompiler(
-        libraryPaths: List<String>,
-        junitLibraryPaths: List<String>,
-    ): KotlinTestCompiler {
-        // kotlinc should be under `[kotlinSDKHomeDirectory]/bin/kotlinc`
```
Comment (SergeyDatskiv) [inline src/main/kotlin/org/jetbrains/research/testspark/tools/factories/TestCompilerFactory.kt:52]: I'll add the comment back after I get the merge request reviewed so that if there are more issues, I can change them at once.

**Comment by Hello-zoka** [comment]
Probably closes #320

File: core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt
Comment (Vladislav0Art) [inline core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt:1]: A TODO comment on line 38 can be removed now:
```
TODO(vartiukhov): find a way to locate `java` on Windows
```

**Comment by Vladislav0Art** [comment]
Kotlin compilation modulo this [issue](https://github.com/JetBrains-Research/TestSpark/issues/407) works on my Windows now.

File: core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt [hunk 2]
```diff
@@ -13,9 +13,12 @@ class KotlinTestCompiler(
     libPaths: List<String>,
     junitLibPaths: List<String>,
     kotlinSDKHomeDirectory: String,
+    javaHomeDirectoryPath: String,
 ) : TestCompiler(libPaths, junitLibPaths) {
     private val logger = KotlinLogging.logger { this::class.java }
     private val kotlinc: String
+    // Direct declaration in constructor requires changes to TestCompiler, so we declare it here.
+    private val javaHomeDirectoryPath = javaHomeDirectoryPath
```
Comment (Vladislav0Art) [inline core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt:21]: > requires changes to TestCompiler

What changes does it need? I found it visible to write like this and it worked fine:
```kotlin
class KotlinTestCompiler(
    ...,
    private val javaHomeDirectoryPath: String,
) : TestCompiler(..) {
  ..
}
```

File: src/main/kotlin/org/jetbrains/research/testspark/tools/factories/TestCompilerFactory.kt [hunk 3]
```diff
@@ -24,33 +24,41 @@ object TestCompilerFactory {
...
         // TODO add the warning window that for Java we always need the javaHomeDirectoryPath
         return when (language) {
-            SupportedLanguage.Java -> createJavaCompiler(project, libraryPaths, junitLibraryPaths, javaHomeDirectory)
-            SupportedLanguage.Kotlin -> createKotlinCompiler(libraryPaths, junitLibraryPaths)
+            SupportedLanguage.Java -> {
+                val javaSDKHomePath = findJavaSDKHomePath(javaHomeDirectory, project)
+                JavaTestCompiler(libraryPaths, junitLibraryPaths, javaSDKHomePath)
+            }
+            SupportedLanguage.Kotlin -> {
+                val javaSDKHomePath = findJavaSDKHomePath(javaHomeDirectory, project) // Kotlinc relies on java to compile kotlin files.
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/tools/factories/TestCompilerFactory.kt:32]: **nitpick**: I'd comment on the line above. It is 120 characters long, which is quite long compared to the neighboring lines.

**Review by Vladislav0Art — APPROVED** [review]
Approved with minor suggestions. There is a question about the Java home path param in the Kotlin compiler.

File: core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt
Comment (SergeyDatskiv) [reply core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt:1]: Removed it, it should be fine now. Thanks for spotting it! 🙂

File: core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt (hunk 2 above)
Comment (SergeyDatskiv) [reply core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt]: You are right, I have no clue what I was doing before. 😅 Thanks for pointing that out; it should be fixed now. 👍

File: src/main/kotlin/org/jetbrains/research/testspark/tools/factories/TestCompilerFactory.kt (hunk 3 above)
Comment (SergeyDatskiv) [reply src/main/kotlin/org/jetbrains/research/testspark/tools/factories/TestCompilerFactory.kt]: You are right, this is something I realised after committing that it would probably be nicer if I placed the comment above the line rather than next to it. Should be fixed now. Thank you! 🙂

**Comment by Vladislav0Art** [comment]
Since we decided to do rebasing, the last commit should be reverted, and the entire branch rebased on `development.`

**Comment by SergeyDatskiv** [comment]
@Vladislav0Art 

> 1. Since we decided to do rebasing, the last commit should be reverted, and the entire branch rebased on `development` (if possible without way to much time spent).

This will create a revert commit, are we okay with that? 

> 2. Mind to close the issue Iurii mentioned [above](https://github.com/JetBrains-Research/TestSpark/pull/412#issuecomment-2465445728).

Do I need to manually check that issue 320 is also fixed? Because Iurii mentioned that it "probably closes" the issue.

Thanks!

**Comment by Vladislav0Art** [comment]
@SergeyDatskiv 
> This will create a revert commit, are we okay with that?

Oh! I think we can do it better: when you start git rebase, type `git rebase --edit-todo` and remove the line with the merge commit [0fab360](https://github.com/JetBrains-Research/TestSpark/pull/412/commits/0fab360a669a25cc6607ef4c90e5286f5281892d) (+ add `break` at the end to see the final result before rebase completes). 

```diff
# rebase's todo list opened via `rebase --edit-todo`
[some other commits above]
- 0fab360 Merge branch 'development' into SergeyDatskiv/bugfix/410-javac-path-...
+ break (at the end)
```
