### PR TITLE
NullPointerException during attempt of LLM test generation on a custom project

### LINKED ISSUE #135: `NullPointerException` during attempt of LLM test generation on a custom project
**Describe the bug**
I merely try to execute an LLM unit test generation on the file `org.csc.java.spring2023.multithreading.CustomThreadPool` (see zip-archive with the project attached) and it results in the following error:
```log
java.lang.NullPointerException: getText(...) must not be null
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.getSignatureString(PromptManager.kt:170)
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.createMethodRepresentation(PromptManager.kt:115)
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.createClassRepresentation(PromptManager.kt:126)
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.generatePrompt$lambda$4(PromptManager.kt:57)
	at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:271)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:845)
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.generatePrompt(PromptManager.kt:53)
	at org.jetbrains.research.testspark.tools.llm.generation.LLMProcessManager.runTestGenerator(LLMProcessManager.kt:90)
	at org.jetbrains.research.testspark.tools.Pipeline$runTestGeneration$1.run(Pipeline.kt:67)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
[csc-java-course-spring-2023-thread-pool-Vladislav0Art.zip](https://github.com/JetBrains-Research/TestSpark/files/14723926/csc-java-course-spring-2023-thread-pool-Vladislav0Art.zip)

**To Reproduce**
1. Open the project and select `corretto-11` JDK (JDK might no be important).
2. Navigate to the mentioned file (maybe it can be reproduced for any file) 
3. Execute the LLM test generation.

**Expected behavior**
Successful test generation.

**Screenshots**

Screenshot 2024-03-22 at 15 24 39

### LINKED ISSUE #137: java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
**Describe the bug**
```
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:106)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:142)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:87)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:245)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:228)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:100)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:93)
	at org.jetbrains.research.testspark.tools.Pipeline.<init>(Pipeline.kt:43)
	at org.jetbrains.research.testspark.tools.llm.Llm.createLLMPipeline(Llm.kt:135)
	at org.jetbrains.research.testspark.tools.llm.Llm.generateTestsForClass(Llm.kt:79)
	at org.jetbrains.research.testspark.tools.Manager$Companion.generateTestsForClassByLlm(Manager.kt:53)
	at org.jetbrains.research.testspark.actions.TestSparkAction$TestSparkActionWindow.startLLMGeneration(TestSparkAction.kt:343)
	at org.jetbrains.research.testspark.actions.TestSparkAction$TestSparkActionWindow.addListeners$lambda$9(TestSparkAction.kt:315)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4969)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4583)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4524)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2809)
...
```

**To Reproduce**
1. Run the generation

### PR DESCRIPTION
**Pull request by arksap2002**
# Description of changes made
Some parts of the planning code should be wrapped in the block `ApplicationManager.getApplication().runWriteAction` so that `Slow operations are prohibited on EDT`. In this PR we add 2 such blocks.

# Other notes
Closes #135
Closes #137 

- [x] I have checked that I am merging into correct branch

### CODE REVIEW

File: src/main/kotlin/org/jetbrains/research/testspark/tools/Pipeline.kt [hunk 1]
```diff
@@ -42,7 +43,7 @@ class Pipeline(
     fileUrl: String?,
     private val packageName: String,
 ) {
-    val projectContext: ProjectContext
+    lateinit var projectContext: ProjectContext
```
Comment (pderakhshanfar) [inline src/main/kotlin/org/jetbrains/research/testspark/tools/Pipeline.kt:46]: Why it should be lateinit? Please add more comments

File: src/main/kotlin/org/jetbrains/research/testspark/tools/llm/Llm.kt [hunk 2]
```diff
@@ -32,27 +34,38 @@ class Llm(override val name: String = "LLM") : Tool {
...
         val maxPolymorphismDepth = SettingsArguments.maxPolyDepth(0)
 
         val cutPsiClass: PsiClass = getSurroundingClass(psiFile, caretOffset)!!
 
-        var currentPsiClass = cutPsiClass
-        for (index in 0 until maxPolymorphismDepth) {
-            if (!classesToTest.contains(currentPsiClass)) {
-                classesToTest.add(currentPsiClass)
-            }
+        ApplicationManager.getApplication().runReadAction(
```
Comment (pderakhshanfar) [inline src/main/kotlin/org/jetbrains/research/testspark/tools/llm/Llm.kt:50]: This code snippet is getting bigger. Maybe it can be a function for better readability

**Review by pderakhshanfar — CHANGES_REQUESTED** [review]
Please add comments. Also, update the PR's description and explain what was the problem and how it is fixed.

**Review by pderakhshanfar — APPROVED** [review]
