### PR TITLE
Object files relocation

### LINKED ISSUE #209: Object files relocation
**Describe the bug**
Moving common ui files to uiUtlis folder to improve logic of the project.

### PR DESCRIPTION
**Pull request by arksap2002**
# Description of changes made
Refactoring the ui utils object files and deleting local helpers.
Most of the changes are the same due to the import path changing.
Closes #209 

# Why is merge request needed
Improving the logic of the files location.

- [x] I have checked that I am merging into correct branch

### CODE REVIEW

**Comment by NikolaiSviridov** [comment]
`CoverageVisualisationTabFactory` is not a factory and needs to be refactored/renamed in the future

**Review by NikolaiSviridov — APPROVED** [review]

File: src/main/kotlin/org/jetbrains/research/testspark/display/coverage/CoverageVisualisationTabFactory.kt [hunk 1]
```diff
@@ -228,6 +231,55 @@ class CoverageVisualisationTabFactory(private val project: Project, private val
...
+            /**
+             * Returns the value at index.
+             *
+             * @param rowIndex index of row
+             * @param columnIndex index of column
+             * @return value at row
+             */
+            override fun getValueAt(rowIndex: Int, columnIndex: Int): Any {
+                return data[rowIndex * 4 + columnIndex]
+            }
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/display/coverage/CoverageVisualisationTabFactory.kt:264]: [unimportant] here as well:
```kotlin
override fun getValueAt(rowIndex: Int, columnIndex: Int): Any
           = data[rowIndex * 4 + columnIndex]
```

File: src/main/kotlin/org/jetbrains/research/testspark/display/coverage/CoverageVisualisationTabFactory.kt [hunk 2]
```diff
@@ -228,6 +231,55 @@ class CoverageVisualisationTabFactory(private val project: Project, private val
...
+        }
+
+        val table = JBTable(tableModel)
+
+        val mainPanel = ScrollPaneFactory.createScrollPane(table)
+
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/display/coverage/CoverageVisualisationTabFactory.kt:270]: Would you mind placing a comment above the `mainPanel` mentioning that the below panel is for rendering coverage stats? So that it can be easily perceived at a glance.

File: src/main/kotlin/org/jetbrains/research/testspark/actions/llm/LLMSampleSelectorFactory.kt [hunk 3]
```diff
@@ -172,4 +180,55 @@ class LLMSampleSelectorFactory(private val project: Project) : PanelFactory {
             testSamplePanelFactory.enabledComponents(isEnabled)
         }
     }
+
+    /**
+     * Retrieves a list of test samples from the given project.
+     *
+     * @return A list of strings, representing the names of the test samples.
+     */
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/actions/llm/LLMSampleSelectorFactory.kt:188]: The implementation of this method currently supports only Java (e.g., Java-specific keywords used). Do we want to extend it for Kotlin right at the beginning, or is it for future refactoring?

File: src/main/kotlin/org/jetbrains/research/testspark/actions/llm/LLMSampleSelectorFactory.kt [hunk 4]
```diff
@@ -172,4 +180,55 @@ class LLMSampleSelectorFactory(private val project: Project) : PanelFactory {
...
+        var normalizedImports = imports
+        if (normalizedImports.isNotBlank()) normalizedImports += "\n\n"
+        return normalizedImports +
+            "public class TestSample {\n" +
+            "   $methodCode\n" +
+            "}"
+    }
+
+    private fun createMethodName(psiClass: PsiClass, method: PsiMethod): String =
+        "<html>${psiClass.qualifiedName}#${method.name}</html>"
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/actions/llm/LLMSampleSelectorFactory.kt:233]: [Nitpick] I would rename the method to `createUIPresantableMethodName`. First, I thought this function would create a name akin to a method signature, not HTML.

Maybe this function knows too much about PSI components. How about the following?
```kotlin
private fun createUIPresantableMethodName(classQualifiedName: String, methodName: String): String =
        "<html>${classQualifiedName}#${methodName}</html>"

// ...

val uiMethodName = createUIPresantableMethodName(psiClass.qualifiedName, psiMethod.name)
```

File: src/main/kotlin/org/jetbrains/research/testspark/actions/llm/LLMSampleSelectorFactory.kt [hunk 5]
```diff
@@ -172,4 +180,55 @@ class LLMSampleSelectorFactory(private val project: Project) : PanelFactory {
...
     }
+
+    /**
+     * Retrieves a list of test samples from the given project.
+     *
+     * @return A list of strings, representing the names of the test samples.
+     */
+    private fun collectTestSamples(project: Project, testNames: MutableList<String>, initialTestCodes: MutableList<String>) {
+        val projectFileIndex: ProjectFileIndex = ProjectRootManager.getInstance(project).fileIndex
+        val javaFileType: FileType = FileTypeManager.getInstance().getFileTypeByExtension("java")
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/actions/llm/LLMSampleSelectorFactory.kt:191]: Do we create an implementation for Java only right now? In the future, we will need to refactor it to integrate Kotlin support.

**Review by Vladislav0Art — CHANGES_REQUESTED** [review]
Could you please also fix the typos in the PR description?

**Comment by arksap2002** [comment]
> `CoverageVisualisationTabFactory` is not a factory and needs to be refactored in the future

thank you fixed in the previous PR

File: src/main/kotlin/org/jetbrains/research/testspark/actions/llm/LLMSampleSelectorFactory.kt (hunk 3 above)
Comment (arksap2002) [reply src/main/kotlin/org/jetbrains/research/testspark/actions/llm/LLMSampleSelectorFactory.kt]: This implementation focuses exclusively on the Java language. All future refactorings and extensions to other languages will be in separate PRs

File: src/main/kotlin/org/jetbrains/research/testspark/actions/llm/LLMSampleSelectorFactory.kt (hunk 5 above)
Comment (arksap2002) [reply src/main/kotlin/org/jetbrains/research/testspark/actions/llm/LLMSampleSelectorFactory.kt:190]: This implementation focuses exclusively on the Java language. All future refactorings and extensions to other languages will be in separate PRs. Kate will implement some manager for interaction with other languages

File: src/main/kotlin/org/jetbrains/research/testspark/display/TestCasePanel.kt [hunk 6]
```diff
@@ -58,23 +57,25 @@ import javax.swing.JOptionPane
...
-class TestCasePanelBuilder(
+class TestCasePanel(
     private val project: Project,
     private val testCase: TestCase,
     editor: Editor,
     private val checkbox: JCheckBox,
     private val uiContext: UIContext?,
     private val report: Report,
-    private val coverageVisualisationTabBuilder: CoverageVisualisationTabBuilder,
+    private val coverageVisualisationTabFactory: CoverageVisualisationTabBuilder,
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/display/TestCasePanel.kt:69]: Should not this variable be named `coverageVisualisationTabBuilder`?

File: src/main/kotlin/org/jetbrains/research/testspark/display/TestCasePanel.kt [hunk 7]
```diff
@@ -344,6 +328,18 @@ class TestCasePanelBuilder(
...
+        updateBorder(error)
+        if (error.isNullOrBlank()) {
+            errorLabel.isVisible = false
+        } else {
+            errorLabel.toolTipText = error
+            errorLabel.isVisible = true
+        }
+
+        runTestButton.isEnabled = previousError(testCase.testCode) == null
+    }
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/display/TestCasePanel.kt:341]: The function name `previousError` is not very good. `getPreviousError`/extractPreviousError` is better.

File: src/main/kotlin/org/jetbrains/research/testspark/display/TestCasePanel.kt [hunk 8]
```diff
@@ -604,10 +602,16 @@ class TestCasePanelBuilder(
...
+        ReportUpdater.removeTestCase(report, testCase, coverageVisualisationTabFactory, generatedTestsTabData)
         GenerateTestsTabHelper.update(generatedTestsTabData)
     }
 
+    private fun previousError(code: String) = trimmedCodeToError[trimCode(code)]
+
+    private fun saveErrorForCode(code: String, error: String?) {
+        trimmedCodeToError[trimCode(code)] = error
+    }
+
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/display/TestCasePanel.kt:614]: There are better solutions than having the code as an index in the map. The current solution is error-prone, and we cannot guarantee that the code pieces are unique.


**Do these code pieces represent the test cases generated by the LLM?** 
In this case, we have indexes that can be used as map keys as well (we would need to seal the initial index for each test case so that after test case deletion, indexes are still the same).

File: src/main/kotlin/org/jetbrains/research/testspark/display/TestSparkDisplayBuilder.kt [hunk 9]
```diff
@@ -41,6 +41,11 @@ class TestSparkDisplayBuilder {
         toolWindow!!.show()
 
         generatedTestsTabBuilder!!.getRemoveAllButton().addActionListener {
+            if (generatedTestsTabBuilder!!.getGeneratedTestsTabData().testCaseNameToPanel.isEmpty()) {
+                clear()
+                return@addActionListener
+            }
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/display/TestSparkDisplayBuilder.kt:47]: I do not understand what exactly this if-statement does. Could you explain (and mention it in the comment above the if-statement as well)?

File: src/main/kotlin/org/jetbrains/research/testspark/display/generatedTestsTab/GeneratedTestsTabBuilder.kt [hunk 10]
```diff
@@ -118,16 +119,16 @@ class GeneratedTestsTabBuilder(
...
 
             // Add a checkbox to select the test
-            val checkbox = JCheckBox()
-            checkbox.isSelected = true
-            checkbox.addItemListener {
-                generatedTestsTabData.testsSelected -= (1 - 2 * checkbox.isSelected.compareTo(false))
+            val testCaseSelectedCheckbox = JCheckBox()
+            testCaseSelectedCheckbox.isSelected = true
+            testCaseSelectedCheckbox.addItemListener {
+                generatedTestsTabData.testsSelected -= (1 - 2 * testCaseSelectedCheckbox.isSelected.compareTo(false))
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/display/generatedTestsTab/GeneratedTestsTabBuilder.kt:129]: This is a very tricky formula. Could you comment on it in the code and move the expression into a named variable so it is easy to understand what it does?

Comment (Vladislav0Art) [reply src/main/kotlin/org/jetbrains/research/testspark/display/generatedTestsTab/GeneratedTestsTabBuilder.kt:129]: It seems to be equivalent to:
```kotlin
generatedTestsTabData.testsSelected += (2 * testCaseSelectedCheckbox.isSelected.compareTo(false) - 1)
```

**Review by Vladislav0Art — CHANGES_REQUESTED** [review]

**Review by Vladislav0Art — APPROVED** [review]
The comments I left may be addressed in another PR.

File: src/main/kotlin/org/jetbrains/research/testspark/display/TestCasePanel.kt (hunk 8 above)
Comment (arksap2002) [reply src/main/kotlin/org/jetbrains/research/testspark/display/TestCasePanel.kt]: created an issue
