### PR TITLE
[#276] Update thread management in the `returnOriginalEditorBackground` method

### LINKED ISSUE #276: Potential data races in `TestCaseDisplayService.returnOriginalEditorBackground`
**Describe the bug**
The method has the following implementation:
```kotlin
private fun returnOriginalEditorBackground(editor: EditorTextField) {
    Thread {
        Thread.sleep(10000)
        editor.background = defaultEditorColor // <- non-atomic + no mutex lock
    }.start()
}
```

1. The `editor.background` is not atomic or covered with a mutex lock before the modification. There is room for data races here, which may not manifest themselves due to a lack of thread contention.

[ChatGPT]: Accessing and modifying UI components from a background thread can cause thread safety issues. In many GUI frameworks, UI components should only be accessed and modified from the main (UI) thread. Modifying them from a background thread can lead to race conditions, crashes, or undefined behavior.

**Expected behavior**
No space for the data race must be available.

### PR DESCRIPTION
**Pull request by arksap2002**
# Description of changes made
Improved the thread management in the `returnOriginalEditorBackground` method by adding ProgressManager instance; and processing the indicator cancellation. 

# Other notes
Closes #276 

- [x] I have checked that I am merging into correct branch

### CODE REVIEW

File: src/main/kotlin/org/jetbrains/research/testspark/display/coverage/CoverageRenderer.kt [hunk 1]
```diff
@@ -219,12 +227,31 @@ class CoverageRenderer(
...
+                    val numberOfIterations = 100
+                    repeat(numberOfIterations) {
+                        if (indicator.isCanceled) return
+                        Thread.sleep(timeWithHighlightedBackground / numberOfIterations)
+                    }
+                }
+
+                override fun onFinished() {
+                    super.onFinished()
+                    synchronized(editorLock) {
```
Comment (stephanlukasczyk) [inline src/main/kotlin/org/jetbrains/research/testspark/display/coverage/CoverageRenderer.kt:249]: Is there an advantage/reason to use this `editorLock`? Wouldn't `synchronized(this)` do the same thing, too? In that case the `editorLock` field could also be removed.

**Review by stephanlukasczyk — APPROVED** [review]
I am not sure about the `synchronized` block, I've added an annotation to. If the field is necessary, feel free to merge it without changes.
