### PR TITLE
[#160] Support of ExtendWith annotation

### LINKED ISSUE #160: `JavaClassBuilderHelper` does not support `@ExtendWith` from JUnit5
**Describe the bug**
The `JavaClassBuilderHelper` class has the following in its `printUpperPart` method:
```kotlin
if (runWith.isNotBlank()) {
     testText += "@RunWith($runWith)\n"
}
```
i.e., there is a hard-coded `RunWith` annotation, although it should vary depending on the JUnit version used. It can be implemented via `RunWithAnnotationMeta` provided in `JUnitVersion` class as follows:
```kotlin
if (runWith.isNotBlank()) {
    val annotation = junitVersion.runWithAnnotationMeta.annotationName // either 'RunWith' or 'ExtendWith'
    testText += "@${annotation}($runWith)\n"
}
```

## Example:

1. Prompt:
````log
Generate unit tests in Java for Calc.
All tests should be for JUnit 5.
All test cases MUST be inserted into a single test suite.
Name all methods according to the template - [MethodUnderTest][Scenario]Test, and use only English letters.
Use @ExtendWith for the generated test suite.
The source code of class under test is as follows:
```
public class Calc {
    public int sum(int a, int b) {
        return a + b;
    }

    public int multiply(int a, int b) {
        return a * b;
    }
}
```
````
2. Response:
````log
```java
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.extension.Extensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.extension.RegisterExtension;

@ExtendWith(CalcTestSuite.class)
public class CalcTestSuite {

    private final Calc calc = new Calc();

    @Test
    public void sumPositiveNumbersTest() {
        int a = 5;
        int b = 7;
        int expected = 12;
        Assertions.assertEquals(expected, calc.sum(a, b));
    }

    @Test
    public void sumNegativeNumbersTest() {
        int a = -5;
        int b = -7;
        int expected = -12;
        Assertions.assertEquals(expected, calc.sum(a, b));
    }

    @Test
    public void sumZeroTest() {
        int a = 0;
        int b = 0;
        int expected = 0;
        Assertions.assertEquals(expected, calc.sum(a, b));
    }

    @Test
    public void multiplyPositiveNumbersTest() {
        int a = 5;
        int b = 7;
        int expected = 35;
        Assertions.assertEquals(expected, calc.multiply(a, b));
    }

    @Test
    public void multiplyNegativeNumbersTest() {
        int a = -5;
        int b = -7;
        int expected = 35;
        Assertions.assertEquals(expected, calc.multiply(a, b));
    }

    @Test
    public void multiplyByZeroTest() {
        int a = 5;
        int b = 0;
        int expected = 0;
        Assertions.assertEquals(expected, calc.multiply(a, b));
    }
}
```
````
3. Compilation error:
````log
'/path/to/test/files/GeneratedSumPositiveNumbersTest.java:8: error: cannot find symbol @RunWith(CalcTestSuite.class) ^  symbol: class RunWith
````

### PR DESCRIPTION
**Pull request by Hello-zoka**
# Description of changes made
Previously, both `ExtendWith` and `RunWith` annotations were replaced with `RunWith` ones since it is available in both JUnit versions. This fix makes any annotation used in JUnit 4 be replaced with `RunWith`, while for JUnit 5 replaces it with `ExtendWith`(which is a superset of runWith).  Also introduces more logical variable naming.

# Why is a merge request needed
These changes have the potential to lower the amount of compilation errors for JUnit 5 tests, in case of using unique for `ExtenWith` annotation APIs.

# Other notes
Closes #160

- [x] I have checked that I am merging into the correct branch

### CODE REVIEW

File: src/main/kotlin/org/jetbrains/research/testspark/display/utils/java/JavaDisplayUtils.kt [hunk 1]
```diff
@@ -141,8 +141,8 @@ class JavaDisplayUtils : DisplayUtils {
                 psiJavaFile = (PsiManager.getInstance(project).findFile(virtualFile!!) as PsiJavaFile)
                 psiClass = PsiElementFactory.getInstance(project).createClass(className.split(".")[0])
 
-                if (uiContext!!.testGenerationOutput.runWith.isNotEmpty()) {
-                    psiClass!!.modifierList!!.addAnnotation("RunWith(${uiContext.testGenerationOutput.runWith})")
+                if (uiContext!!.testGenerationOutput.annotation.isNotEmpty()) {
+                    psiClass!!.modifierList!!.addAnnotation("RunWith(${uiContext.testGenerationOutput.annotation})")
```
Comment (stephanlukasczyk) [inline src/main/kotlin/org/jetbrains/research/testspark/display/utils/java/JavaDisplayUtils.kt:145]: Not sure if I understand this correctly: in case the `annotation` is *not* empty, this adds an annotation to the modifier list, that says `@RunWith(...)`, right?

Now, while this is for sure fine for JUnit 4, wasn't the whole point of this PR to use different annotations for JUnit 4 and 5, i.e., `@ExtendWith(...)` for the latter? Could you please clarify, whether a change is missing here, or whether I am misunderstanding this somehow?

File: src/main/kotlin/org/jetbrains/research/testspark/display/utils/kotlin/KotlinDisplayUtils.kt [hunk 2]
```diff
@@ -144,9 +144,9 @@ class KotlinDisplayUtils : DisplayUtils {
                 val ktPsiFactory = KtPsiFactory(project)
                 ktClass = ktPsiFactory.createClass("class ${className.split(".")[0]} {}")
 
-                if (uiContext!!.testGenerationOutput.runWith.isNotEmpty()) {
+                if (uiContext!!.testGenerationOutput.annotation.isNotEmpty()) {
                     val annotationEntry =
-                        ktPsiFactory.createAnnotationEntry("@RunWith(${uiContext.testGenerationOutput.runWith})")
+                        ktPsiFactory.createAnnotationEntry("@RunWith(${uiContext.testGenerationOutput.annotation})")
```
Comment (stephanlukasczyk) [inline src/main/kotlin/org/jetbrains/research/testspark/display/utils/kotlin/KotlinDisplayUtils.kt:149]: Not sure if I understand this correctly: in case the `annotation` is *not* empty, this adds an annotation to the modifier list, that says `@RunWith(...)`, right?

Now, while this is for sure fine for JUnit 4, wasn't the whole point of this PR to use different annotations for JUnit 4 and 5, i.e., `@ExtendWith(...)` for the latter? Could you please clarify, whether a change is missing here, or whether I am misunderstanding this somehow?

**Review by stephanlukasczyk — COMMENTED** [review]
Could you please provide a clarification on my question in the `JavaDisplayUtils` and `KotlinDisplayUtils`? I am not sure whether I misunderstand it or whether there is a change missing.

File: src/main/kotlin/org/jetbrains/research/testspark/display/utils/java/JavaDisplayUtils.kt (hunk 1 above)
Comment (Hello-zoka) [reply src/main/kotlin/org/jetbrains/research/testspark/display/utils/java/JavaDisplayUtils.kt:145]: Yes, a change is missing here. I was refactoring only variable names in these files and didn't notice `RunWith`

**Comment by Hello-zoka** [comment]
> Could you please provide a clarification on my question in the `JavaDisplayUtils` and `KotlinDisplayUtils`? I am not sure whether I misunderstand it or whether there is a change missing.

Yes, changes were missed. Fixed.

**Review by stephanlukasczyk — APPROVED** [review]
