### PR TITLE
Fix error message window size

### LINKED ISSUE #150: Fix error message window size
**Describe the bug**
No message in the error window

**To Reproduce**
1. Generate tests, sometimes, you'll see an error

**Expected behavior**

**Screenshots**
In the file
Screenshot 2023-12-01 at 4 04 56 PM

### PR DESCRIPTION
**Pull request by arksap2002**
# Description of changes made
In the case of a long error message, the window on which it is displayed cuts the text. To fix this, I added `<br/>` every 100 characters to reduce the width of the text, since the style of this text is `html`.

# Other notes
Closes #150 

- [x] I have checked that I am merging into correct branch

### CODE REVIEW

File: src/main/kotlin/org/jetbrains/research/testspark/display/ErrorMessageNormalizer.kt [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+     * Normalizes an error message by inserting "<br/>" tags after every 300 characters,
+     * except if there is already a "<br/>" tag within the blockSize characters.
+     * If the string length is a multiple of blockSize and the last character is a "<br/>" tag,
+     * it is removed from the result.
+     *
+     * @param error The error message to be normalized.
+     * @return The normalized error message.
+     */
+    fun normalize(error: String): String {
+        // set default parameters
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/display/ErrorMessageNormalizer.kt:14]: This function is a candidate for testing, as the implementation is somewhat tricky and is better ensured by unit tests.

File: src/main/kotlin/org/jetbrains/research/testspark/display/ErrorMessageNormalizer.kt [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+            if (!substring.contains(separator)) {
+                builder.append(substring).append(separator)
+            } else {
+                builder.append(substring)
+            }
+
+            lastIndex = nextIndex
+        }
+
+        // remove the last <br/> if the string length is a multiple of 300 and it didn't have <br/>
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/display/ErrorMessageNormalizer.kt:36]: `... multiple of 300` -> `... multiple of the block size`

File: src/main/kotlin/org/jetbrains/research/testspark/display/ErrorMessageNormalizer.kt [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+        if (builder.endsWith(separator) && (error.length % blockSize == 0)) {
+            builder.setLength(builder.length - separator.length)
+        }
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/display/ErrorMessageNormalizer.kt:39]: I think the `setLength` is not the best choice for removal, it is better to use the dedicated method `deleteRange`:
```kotlin
// please ensure that the left index is correct
val begin = builder.lastIndexOf("<br>");
builder.deleteRange(begin, begin + "<br>".length);
// OR:
builder.deleteRange(builder.length - "<br>".length, builder.length);
```

**Review by Vladislav0Art — CHANGES_REQUESTED** [review]

File: src/test/kotlin/org/jetbrains/research/testspark/helper/ErrorMessageNormalizerTest.kt [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+
+import org.junit.jupiter.api.Assertions.assertEquals
+import org.junit.jupiter.api.Test
+
+class ErrorMessageNormalizerTest {
+
+    /**
+     * Test with a string length less than BLOCK_SIZE and no separators.
+     */
+    @Test
```
Comment (Vladislav0Art) [inline src/test/kotlin/org/jetbrains/research/testspark/helper/ErrorMessageNormalizerTest.kt:11]: We also want to test the following condition in the implementation:
```kotlin
if (builder.endsWith(SEPARATOR) && (error.length % BLOCK_SIZE == 0)
```
There should be a test with a message whose size is multiple of `BLOCK_SIZE`, and the message should end with the `SEPARATOR`.

**Review by Vladislav0Art — APPROVED** [review]
