### PR TITLE
Restrict TestSpark action to suitable code types and fix generation for a line

### LINKED ISSUE #247: [Java] Wrong enum class parsing
# Description

There is a bug in PSI parsing, when there is a cursor inside `enum`. 

```
// Enum definition
enum MyEnum {
    FIRST(1),
    SECOND(2),
    THIRD(3);

    private final int value;

    MyEnum(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    void enumMethod() {
        System.out.println("This is a method in an enum class.");
    }
}
```

1. If the cursor is placed within an enum on a line containing text, the only option displayed in the window is the ability to test that specific line.
2. When the cursor is in a blank line, there are no possible testing options displayed in the panel.

### LINKED ISSUE #249: [Java] Empty line parsing
## Description

When a cursor is within the empty line and we make a right clock, then there is an option to use TestSpark. In the following window there are no options.

image

I think that the behavior solution is to disable "TestSpark" option in the window that appear from right click.

### LINKED ISSUE #336: java.lang.NullPointerException in case of non-Java and non-Kotlin file for generation
**Describe the bug**
```
java.lang.NullPointerException
	at org.jetbrains.research.testspark.actions.TestSparkAction$TestSparkActionWindow.getPsiHelper(TestSparkAction.kt:118)
	at org.jetbrains.research.testspark.actions.TestSparkAction$TestSparkActionWindow.<init>(TestSparkAction.kt:121)
	at org.jetbrains.research.testspark.actions.TestSparkAction.actionPerformed(TestSparkAction.kt:71)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.kt:305)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks$lambda$4(ActionUtil.kt:276)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:1161)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.kt:275)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction$lambda$5(ActionMenuItem.kt:269)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.kt:260)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem._init_$lambda$0(ActionMenuItem.kt:71)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed$lambda$4(ActionMenuItem.kt:102)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.kt:101)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:525)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:558)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4969)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4583)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4524)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2809)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:698)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:637)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:584)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:138)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:129)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:584)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:362)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:361)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:361)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1021)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1021)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:209)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:398)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**To Reproduce**
1. Go to `.py` class 
2. Generate tests for it with TestSpark
3. See error

### LINKED ISSUE #352: Error during asking to generate tests for a line outside a method
**Describe the bug**
Error during asking to generate tests for the external line.

```
java.lang.NullPointerException
	at org.jetbrains.research.testspark.java.JavaPsiHelper.collectClassesToTest(JavaPsiHelper.kt:93)
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager._get_classesToTest_$lambda$0(PromptManager.kt:51)
	at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:271)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:845)
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.getClassesToTest(PromptManager.kt:48)
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.<init>(PromptManager.kt:60)
	at org.jetbrains.research.testspark.tools.llm.Llm.generateTestsForLine(Llm.kt:192)
	at org.jetbrains.research.testspark.actions.TestSparkAction$TestSparkActionWindow.startUnitTestGenerationTool(TestSparkAction.kt:366)
	at org.jetbrains.research.testspark.actions.TestSparkAction$TestSparkActionWindow.startLLMGeneration(TestSparkAction.kt:387)
	at org.jetbrains.research.testspark.actions.TestSparkAction$TestSparkActionWindow.addListeners$lambda$9(TestSparkAction.kt:330)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4969)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4583)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4524)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2809)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:698)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:637)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:584)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:138)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:129)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:584)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:362)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:361)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:361)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1021)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1021)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:209)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:398)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**To Reproduce**
1. Generate tests for package line'
2. See error

**Expected behavior**
It better to disable to generate tests for lines outside the classes for Java.

### LINKED ISSUE #377: Insufficient context about the surrounding method for line-based test generation
Line-based test generation doesn't include information about the class, a line belongs to. For example, in method generation we have smth like: `Generate unit tests in kotlin for org.example.Calc.mul to achieve 100% line coverage for this method.`; i.e., we mention the package name and the name of a class that contains this method. It makes it easier for LLM to instantiate the class and test the method. 

When we generate tests for a line and its context becomes a surrounding method, we never mention the class containing this method. For example, when asked to generate a test for the line 'return a + b' in the following code:
```kotlin
class Calc {
    fun sum(a: Int, b: Int): Int {
        return a + b
    }
 }
``` 
LLM struggles with generating `Calc().sum()` calls and spends attempts on generating uncompilable `sum()` calls. This leads to unnecessary feedback cycle iterations.

This problem became even more crucial if it attempted to generate a test for a line inside a companion object or its method. LLM doesn't know how to call such a function.

**_Solution_**: includes information about the class surrounding the line if such is present. Do not forget to treat the case when the line's context is a top-level function (in Kotlin)!

_Based on this [comment](https://github.com/JetBrains-Research/TestSpark/pull/344#issuecomment-2397800218)._

### PR DESCRIPTION
**Pull request by arksap2002**
# Description of changes made

The PR fixes the following issues:
1. Prohibits action use when non-Java and non-Kotlin file is opened.
2. Prohibits action use when the cursor is placed on a line that is surrounded by neither method nor class. 
3. Successfully generates tests for **a line outside of a method but within a class**.
4. Fixes an issue with line numbering: use 1-based line number invariant for `PsiHelper.getSurroundingLineNumber`; Kotlin used 0-based numbering which attempted the generated prompt, namely it contained a line before the selected one.

See commit subjects and bodies for details.

# What is left
The PR introduces a modification to `core` module (namely, extends the API of `PromptGenerator` with an overload of `generatePromptForLine` method that uses CUT as a line context). Therefore, I (@Vladislav0Art) need to publish a new version of the `core` module.

**TODOs:**
* [x] New core version `4.0.0` is published.

# Other notes
Closes #336 
Closes #352
Closes #247 
Closes #249
Closes #377 

- [x] I have checked that I am merging into the correct branch

### CODE REVIEW

**Comment by pderakhshanfar** [comment]
It does not solve #352 If I ask to generate test for package line in a kotlin project it throws the following exception:

```
java.lang.IllegalStateException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwInvalidState(AbstractProgressIndicatorBase.java:130)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.stop(AbstractProgressIndicatorBase.java:121)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.stop(AbstractProgressIndicatorExBase.java:52)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.delegate(AbstractProgressIndicatorExBase.java:211)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.doDelegateRunningChange(AbstractProgressIndicatorExBase.java:195)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.stop(AbstractProgressIndicatorExBase.java:53)
	at com.intellij.openapi.wm.impl.status.InfoAndProgressPanel$MyInlineProgressIndicator.stop(InfoAndProgressPanel.kt:830)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.delegate(AbstractProgressIndicatorExBase.java:211)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.doDelegateRunningChange(AbstractProgressIndicatorExBase.java:195)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.stop(AbstractProgressIndicatorExBase.java:53)
	at com.intellij.openapi.progress.util.ProgressWindow.stop(ProgressWindow.java:285)
	at org.jetbrains.research.testspark.display.custom.IJProgressIndicator.stop(IJProgressIndicator.kt:32)
	at org.jetbrains.research.testspark.tools.ToolUtils.isProcessCanceled(ToolUtils.kt:117)
	at org.jetbrains.research.testspark.tools.ToolUtils.isProcessStopped(ToolUtils.kt:112)
	at org.jetbrains.research.testspark.tools.Pipeline$runTestGeneration$1.run(Pipeline.kt:107)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

File: java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiHelper.kt [hunk 1]
```diff
@@ -26,6 +26,9 @@ class JavaPsiHelper(private val psiFile: PsiFile) : PsiHelper {
 
     override val language: SupportedLanguage get() = SupportedLanguage.Java
 
+    override fun availableForGeneration(e: AnActionEvent): Boolean =
+        getCurrentListOfCodeTypes(e).map { it.first }.toList().contains(CodeType.CLASS)
```
Comment (Hello-zoka) [inline java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiHelper.kt:30]: Why check only for classes, while in Kotlin, check is for any codeType?

Comment (Vladislav0Art) [reply java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiHelper.kt:30]: I suspect it should be `isNotEmpty()` instead of `contains`, shouldn't it?

**Comment by Vladislav0Art** [comment]
As @pderakhshanfar metioned above, if you attempt generation on an `import` you'l' get an exception. In my case, it was:
```
java.lang.NullPointerException
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.getMethodDescriptor(PromptManager.kt:294)
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.generatePrompt$lambda$6(PromptManager.kt:128)
	at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:271)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:845)
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.generatePrompt(PromptManager.kt:69)
	at org.jetbrains.research.testspark.tools.llm.generation.LLMProcessManager.runTestGenerator(LLMProcessManager.kt:105)
	at org.jetbrains.research.testspark.tools.Pipeline$runTestGeneration$1.run(Pipeline.kt:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-09-30 17:18:58,507 [  38600] SEVERE - #c.i.o.p.Task - IntelliJ IDEA 2024.1  Build #IC-241.14494.240
2024-09-30 17:18:58,507 [  38600] SEVERE - #c.i.o.p.Task - JDK: 17.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-09-30 17:18:58,507 [  38600] SEVERE - #c.i.o.p.Task - OS: Mac OS X
2024-09-30 17:18:58,508 [  38601] SEVERE - #c.i.o.p.Task - Plugin to blame: TestSpark version: 0.2.1
2024-09-30 17:18:58,508 [  38601] SEVERE - #c.i.o.p.Task - Last Action: TestSpark.TestSparkActions
2024-09-30 17:18:58,510 [  38603] SEVERE - #c.i.o.a.i.FlushQueue - null
``` 

It is because we assert that a surrounding method exists. In general, we should **quit using `!!`** in TestSpark. It has always dealt us a bad hand: 

Screenshot 2024-09-30 at 17 22 29

**Comment by Vladislav0Art** [comment]
The same error as [here](https://github.com/JetBrains-Research/TestSpark/pull/344#issuecomment-2383519452) occurs if I start generation for a line `(**)` and select `line` as a code construct under test:
```java
public class Calc {
    int a = 10; // (**)

    public int sum(int a, int b) {
        return a + b;
    }

    public int multiply(int a, int b) {
        return a * b;
    }
}
```

File: java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiHelper.kt (hunk 1 above)
Comment (Vladislav0Art) [reply java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiHelper.kt:30]: @arksap2002 Please, leave a comment within the implementation so that it becomes clear from code.

File: langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiComponents.kt [hunk 2]
```diff
@@ -90,6 +90,14 @@ interface PsiClassWrapper {
 interface PsiHelper {
     val language: SupportedLanguage
 
+    /**
+     * Checks if a class is available for generation at the given caret offset.
```
Comment (Vladislav0Art) [inline langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiComponents.kt:94]: > a class is available

I think you meant whether a valid code construct under the current cursor exists, for which it's possible to generate tests. 

You can write:
```java
/**
* Checks if a code construct is valid for unit test generation at the given caret offset
* */
```

File: langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiComponents.kt [hunk 3]
```diff
@@ -90,6 +90,14 @@ interface PsiClassWrapper {
...
+     *
+     * @param e The AnActionEvent representing the current action event.
+     * @return `true` if a class is available for generation at the caret offset, `false` otherwise.
```
Comment (Vladislav0Art) [inline langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiComponents.kt:97]: `if a class is available ..` -> `if a code construct is valid for unit test generation`.

File: src/main/kotlin/org/jetbrains/research/testspark/actions/TestSparkAction.kt [hunk 4]
```diff
@@ -79,9 +79,7 @@ class TestSparkAction : AnAction() {
     override fun update(e: AnActionEvent) {
         val file = e.dataContext.getData(CommonDataKeys.PSI_FILE)!!
         val psiHelper = PsiHelperProvider.getPsiHelper(file)
-        if (psiHelper == null) {
-            // TODO exception
-        }
+        e.presentation.isEnabledAndVisible = psiHelper != null && psiHelper.availableForGeneration(e)
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/actions/TestSparkAction.kt:82]: Brackets around 1st expression for clarity:
```kotlin
e.presentation.isEnabledAndVisible = (psiHelper != null) && psiHelper.availableForGeneration(e)
```
Alternatively, you can write:
```kotlin
e.presentation.isEnabledAndVisible = (psiHelper?.availableForGeneration(e) == true)
```

**Review by Vladislav0Art — CHANGES_REQUESTED** [review]
There are important comments above that identify unfixed bugs. Those should be addressed in this PR to close the issue #352.

File: java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiHelper.kt (hunk 1 above)
Comment (Vladislav0Art) [reply java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiHelper.kt:30]: Put a comment before this method.

File: langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiComponents.kt (hunk 2 above)
Comment (Vladislav0Art) [reply langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiComponents.kt:94]: updated

File: langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiComponents.kt (hunk 3 above)
Comment (Vladislav0Art) [reply langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiComponents.kt:97]: updated

File: src/main/kotlin/org/jetbrains/research/testspark/actions/TestSparkAction.kt (hunk 4 above)
Comment (Vladislav0Art) [reply src/main/kotlin/org/jetbrains/research/testspark/actions/TestSparkAction.kt]: Used the first option.

**Comment by Vladislav0Art** [comment]
> It does not solve #352 If I ask to generate test for package line in a kotlin project it throws the following exception:

Fixed.

**Comment by Vladislav0Art** [comment]
> The same error as [here](https://github.com/JetBrains-Research/TestSpark/pull/344#issuecomment-2383519452) occurs if I start generation for a line `(**)` and select `line` as a code construct under test:

Fixed.

**Comment by Vladislav0Art** [comment]
> As @pderakhshanfar metioned above, if you attempt generation on an `import` you'l' get an exception. In my case, it was:

Fixed.

**Review by Vladislav0Art — COMMENTED** [review]
Introduced modifications that solve the described problems.

**Review by Vladislav0Art — APPROVED** [review]
I must approve the PR to allow its further merge. This approval does not count.

**Comment by Hello-zoka** [comment]
I've found several problems connected with prompting for line generation:
1) It doesn't include information about the class line refers to. For example in method generation we have smth like: `Generate unit tests in kotlin for org.example.Calc.mul to achieve 100% line coverage for this method.`
For example, when asked to generate a test for the line 'return a + b' in the following code:
```kotlin
class Calc {
    fun sum(a: Int, b: Int): Int {
        return a + b
    }
 }
``` 
LLM is struggling with generating `Calc().sum()` calls and spending attempts on generating uncompilable `sum()` calls. This leads to unnecessary feedback cycles iterations.

This problem became even more crucial if attempted to generate a test for a line inside a companion object, or its a method. LLM just don't know anything about how to call such function.

**_Solution_**: includes information about the class surrounding the line if such is present.

2) We are not allowing line generation for empty lines, but it can be asked for comment lines if it is surrounded by class/function. The result will be almost the same as for the whole class test generation, but it's weird

3) Adding to the previous point, there is a strange restriction for such a top-level function:
```kotlin
/// 123 -- not allowed for line generation

// 123 -- allowed for line generation
fun multwice(a: Int) = a * 2
```
**_Solution idea_**: For each line generation, check if it includes something besides comments, open/closed brackets and allow generation only in such case

**Comment by Vladislav0Art** [comment]
> I've found several problems connected with line generation:
> 
> 1. It doesn't include information about the class line refers to. For example in method generation we have smth like: `Generate unit tests in kotlin for org.example.Calc.mul to achieve 100% line coverage for this method.`
>    For example, when asked to generate a test for the line 'return a + b' in the following code:
> 
> ```kotlin
> class Calc {
>     fun sum(a: Int, b: Int): Int {
>         return a + b
>     }
>  }
> ```
> 
> LLM is struggling with generating `Calc().sum()` calls and spending attempts on generating uncompilable `sum()` calls. This leads to unnecessary feedback cycles iterations.
> 
> This problem became even more crucial if attempted to generate a test for a line inside a companion object, or it's method. LLM just don't know anything about how to call such function.
> 
> **_Solution_**: includes information about the class surrounding the line if such is present.
> 
> 2. We are not allowing line generation for empty lines, but it can be asked for comment lines if it is surrounded by class/function. The result will be almost the same as for the whole class test generation, but it's weird
> 3. Adding to the previous point, there is a strange restriction for such a top-level function:
> 
> ```kotlin
> /// 123 -- not allowed for line generation
> 
> // 123 -- allowed for line generation
> fun multwice(a: Int) = a * 2
> ```
> 
> **_Solution idea_**: For each line generation, check if it includes something besides comments, open/closed brackets and allow generation only in such case

@Hello-zoka, I agree with the 2nd and 3rd points; I'll address them in the PR or explain why they should be addressed in a different PR.

At first glance, the first point does not appear to be an easy task, and it does not represent a bug; it is a lack of context. It is a stand-alone issue that should be addressed in a different PR (possibly after the upcoming release). @Hello-zoka, could you create an issue for it?

My main focus, for now, is to close as many issues as possible that yield runtime exceptions and fail the plugin. The aspects regarding line-based test generation mentioned appear minor to me as very few people use line-based test generation compared to method/class-based generation (a good thing to calculate it as a metric! @arksap2002).

CC: @pderakhshanfar

**Comment by Vladislav0Art** [comment]
> I've found several problems connected with line generation:
> 
> 1. It doesn't include information about the class line refers to. For example in method generation we have smth like: `Generate unit tests in kotlin for org.example.Calc.mul to achieve 100% line coverage for this method.`
>    For example, when asked to generate a test for the line 'return a + b' in the following code:
> 
> ```kotlin
> class Calc {
>     fun sum(a: Int, b: Int): Int {
>         return a + b
>     }
>  }
> ```
> 
> LLM is struggling with generating `Calc().sum()` calls and spending attempts on generating uncompilable `sum()` calls. This leads to unnecessary feedback cycles iterations.
> 
> This problem became even more crucial if attempted to generate a test for a line inside a companion object, or it's method. LLM just don't know anything about how to call such function.
> 
> **_Solution_**: includes information about the class surrounding the line if such is present.
> 
> 2. We are not allowing line generation for empty lines, but it can be asked for comment lines if it is surrounded by class/function. The result will be almost the same as for the whole class test generation, but it's weird
> 3. Adding to the previous point, there is a strange restriction for such a top-level function:
> 
> ```kotlin
> /// 123 -- not allowed for line generation
> 
> // 123 -- allowed for line generation
> fun multwice(a: Int) = a * 2
> ```
> 
> **_Solution idea_**: For each line generation, check if it includes something besides comments, open/closed brackets and allow generation only in such case

@Hello-zoka 
Regarding points 2 and 3, I will create a separate issue for them. Both require modifications in how we select PSI elements in `PsiHelper.getCurrentListOfCodeTypes` + it needs additional parsing, which is out of the scope of the current PR.

File: core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/prompt/PromptGenerator.kt [hunk 5]
```diff
@@ -90,4 +90,32 @@ class PromptGenerator(
...
+     * @throws IllegalStateException If any of the required keywords are missing in the prompt template.
+     */
+    fun generatePromptForLine(
+        lineUnderTest: String,
+        interestingClasses: List<ClassRepresentation>,
+        testSamplesCode: String,
+    ): String {
+        val prompt = PromptBuilder(promptTemplates.linePrompt)
+            .insertLanguage(context.promptConfiguration.desiredLanguage)
+            .insertName(lineUnderTest.trim())
```
Comment (Hello-zoka) [inline core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/prompt/PromptGenerator.kt:110]: Add information about context as well(as it was done for class generation)

For another type of generatePromptForLine, you can provide such information using psiHelper(as it was done for method generation)


This will resolve #377

File: src/main/kotlin/org/jetbrains/research/testspark/actions/TestSparkAction.kt [hunk 6]
```diff
@@ -74,14 +74,18 @@ class TestSparkAction : AnAction() {
...
-            // TODO exception
+        val file = e.dataContext.getData(CommonDataKeys.PSI_FILE)
+
+        if (file == null) {
+            e.presentation.isEnabledAndVisible = false
+            return
         }
+
+        val psiHelper = PsiHelperProvider.getPsiHelper(file)
+        e.presentation.isEnabledAndVisible = (psiHelper != null) && psiHelper.availableForGeneration(e)
```
Comment (Hello-zoka) [inline src/main/kotlin/org/jetbrains/research/testspark/actions/TestSparkAction.kt:88]: --> `psiHelper?.availableForGeneration(e) ?: false`

File: src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/PromptManager.kt [hunk 7]
```diff
@@ -57,6 +57,7 @@ class PromptManager(
     /**
      * The `cut` is null when we work with the function outside the class.
      */
+    // TODO: firstOrNull()?
```
Comment (Hello-zoka) [inline src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/PromptManager.kt:60]: Agree, `firstOrNull()` is better

File: src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/PromptManager.kt [hunk 8]
```diff
@@ -124,32 +125,48 @@ class PromptManager(
...
+                         * otherwise use the cut as a context
+                         */
+                        if (psiMethod != null) {
+                            val method = createMethodRepresentation(psiMethod)!!
+                            val interestingClassesFromMethod =
+                                psiHelper.getInterestingPsiClassesWithQualifiedNames(cut, psiMethod)
+                                    .map(this::createClassRepresentation)
+                                    .toList()
+
+                            return@Computable promptGenerator.generatePromptForLine(
```
Comment (Hello-zoka) [inline src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/PromptManager.kt:151]: You can get the package name from psiHelper, to provide more information to prompt generator(as it was done for `CodeType.METHOD`

**Review by Hello-zoka — CHANGES_REQUESTED** [review]
It seems like it is easy to fix #377 by refactoring how you generate prompt for line. From my opinion it have to be in this PR, since it is about "fix generation for line" + #337 depends on the changes from this PR.

File: core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/prompt/PromptGenerator.kt (hunk 5 above)
Comment (Vladislav0Art) [reply core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/prompt/PromptGenerator.kt]: I implemented it in the commits [957bdb0](https://github.com/JetBrains-Research/TestSpark/pull/344/commits/957bdb06e56b56520366b7161d32a75b2e285a9d) and [441ae06](https://github.com/JetBrains-Research/TestSpark/pull/344/commits/441ae06ce627d105cbecc645bbf44cdb165432c0).

Adding only package was not enough, LLM wasn't able to instantiate a class containing a method that surrounds a selected line. Therefore, I insert a list of constructor signatures of the class into a prompt. It allows AI instantiate a class.

File: src/main/kotlin/org/jetbrains/research/testspark/actions/TestSparkAction.kt (hunk 6 above)
Comment (Vladislav0Art) [reply src/main/kotlin/org/jetbrains/research/testspark/actions/TestSparkAction.kt:88]: Thought about it, but I do not like the elvis operation and `?` used in the single expression. Also, it is possible to change it to `psiHelper?.availableForGeneration(e) === true`, but I do not like it either.

Overall, it is just a style preference, and I prefer the current variant.

File: src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/PromptManager.kt (hunk 7 above)
Comment (Vladislav0Art) [reply src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/PromptManager.kt:60]: Did it.

File: src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/PromptManager.kt (hunk 8 above)
Comment (Vladislav0Art) [reply src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/PromptManager.kt:151]: Supplied the package.

**Comment by Vladislav0Art** [comment]
Here is the comment of `PromptGenerator.buildCutDeclaration` method (so that you do not need to fetch the branch):

Screenshot 2024-10-09 at 18 49 52

**Review by Hello-zoka — APPROVED** [review]

**Review by pderakhshanfar — APPROVED** [review]
Nit (and we dont need to resolve it in this issue) TestSpark option is still available when we try to generate test for a test file:
open a test file right click and ask for test generation using TestSpark
