### PR TITLE
Incorrect output in headless mode

### LINKED ISSUE #360: Incorrect console output in headless mode
**Describe the bug**
Running headless mode without xml collection ends with the incorrect message: `[TestSpark Starter] Test generation failed`

**To Reproduce**
run headless mode without coverage

**Expected behavior**
output `[TestSpark Starter] Test generation completed successfully`

**Additional context**
The problem with if/else logic(easy to fix)

### PR DESCRIPTION
**Pull request by Hello-zoka**
Closes #360

### CODE REVIEW

File: src/main/kotlin/org/jetbrains/research/testspark/appstarter/TestSparkStarter.kt [hunk 1]
```diff
@@ -194,18 +194,20 @@ class TestSparkStarter : ApplicationStarter {
...
+                                runTestsWithCoverageCollection(
+                                    project,
+                                    output,
+                                    packageList,
+                                    classPath,
+                                    projectContext,
+                                    projectSDKPath,
+                                    testCompiler,
+                                )
+                            }
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/appstarter/TestSparkStarter.kt:210]: **Nitpick**: You can also add two `println's stating whether coverage is being run or whether no coverage run is requested.

**Review by pderakhshanfar — APPROVED** [review]
