### PR TITLE
[#382, #241] Add isTestableClass and isTestableMethod to determine testable classes and methods

### LINKED ISSUE #241: isTestableClass used inside LLM
```
    /**
     * Checks if the constraints on the selected class are satisfied, so that EvoSuite can generate tests for it.
     * Namely, it is not an enum and not an anonymous inner class.
     *
     * @return true if the constraints are satisfied, false otherwise
     */
    fun isTestableClass(): Boolean {
        return !psiClass.isEnum && psiClass !is PsiAnonymousClass
    }
```

In the description of this method, it is said that we use this function only for checking whether the class meets the EvoSuit requirements. Nevertheless, we use this function in LLM with the mediation of  `getSurroundingMethod` and `getSurroundingClass`. 
     
So we should update either the description or the implementation of functions that use `isTestableClass `. In the second case, we have to update the Kotlin implementation since EvoSuit works with Java only.

### LINKED ISSUE #382: TestSpark can be triggered in a test file
**Describe the bug**
Users can call TestSpark on a test file

**To Reproduce**
1. Go to a test file (e.g., `CarTest.java`)
2. Right-Click on part of the code
3. Call LLM-based test generation on a code snippet in this file
4. It does not throw any error but it does not make sense either

**Expected behavior**
TestSpark should be disabled on a test file

### LINKED ISSUE #462: Kotlin test file is not visible in the test samples list
### Involved Module
- [ ] UI
- [ ] EvoSuite
- [x] LLM
- [ ] Kex
- [ ] Other (please explain)

### Describe the bug
Kotlin test file is not visible in the test samples list.

### To Reproduce
1. Write Kotlin tests
2. Generate tests for LLM
3. Go to test samples list

### Screenshots

https://github.com/user-attachments/assets/926fcfa0-1041-4b64-8705-e3b0d135d601

### PR DESCRIPTION
**Pull request by arksap2002**
# Description of changes made
Imporve checkings of the classes to test and methods to test requirments.

And apply these methods for LLM Samples selection.

# Other notes
Closes #382
Closes #241
Closes #462

- [x] I have checked that I am merging into correct branch

### CODE REVIEW

File: java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt [hunk 1]
```diff
@@ -86,11 +94,26 @@ class JavaPsiClassWrapper(
...
+            psiClass.isEnum ||
+            psiClass.hasModifierProperty(PsiModifier.ABSTRACT) ||
+            psiClass.isAnnotationType ||
+            psiClass is PsiAnonymousClass
+        ) {
+            return false
+        }
+
+        // Check if the class has methods annotated with @Test
+        val areAllMethodsTestable =
```
Comment (stephanlukasczyk) [inline java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt:108]: The name does not reflect what the variable actually holds, namely if there is at least one method annotated with `@Test`. I suggest `hasTestableMethod`.

File: java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt [hunk 2]
```diff
@@ -86,11 +94,26 @@ class JavaPsiClassWrapper(
...
+            psiClass.methods.any { psiMethod: PsiMethod ->
+                JavaPsiMethodWrapper(psiMethod).isTestableMethod()
+            }
+        if (!areAllMethodsTestable) return false
+
+        // Check if the class explicitly subclasses a known test framework class (e.g., TestCase)
+        if (InheritanceUtil.isInheritor(psiClass, "junit.framework.TestCase")) return false
+
```
Comment (stephanlukasczyk) [inline java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt:116]: I see an additional case here: it could be the case that the CUT does not have `@Test` methods but provides fixture methods, e.g., annotated with `@BeforeEach` and is only used as a base class for the actual test classes. I have done this before to group shared logic of multiple tests and I have also seen that elsewhere. In that case, the CUT neither is a testable class, IMHO.

An example could be (minimised to basically nonsense but it show the structure hopefully):

```java
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class Base {
    protected Object foo;

    @BeforeEach
    void setUp() {
        foo = new Object();
    }
}

class FirstTest extends Base {
    @Test
    void test() {
      assert foo != null;
    }
}

class SecondTest extends Base {
  @Test
    void test() {
    assert foo.equals(foo);
  }
}
```

File: kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiClassWrapper.kt [hunk 3]
```diff
@@ -136,4 +136,29 @@ class KotlinPsiClassWrapper(
...
+        if (methods.any { !it.isTestableMethod() }) {
+            return false
+        }
+
+        // Check if the class explicitly subclasses a known test framework class (e.g., TestCase for JUnit)
+        val superClassFqName = superClass?.qualifiedName
+        if (superClassFqName == "junit.framework.TestCase") {
+            return false
+        }
+
```
Comment (stephanlukasczyk) [inline kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiClassWrapper.kt:161]: Similar to my annotation in `JavaPsiClassWrapper` I assume that similar stuff is possible in Kotlin, too, so there might be more cases here.

**Review by stephanlukasczyk — CHANGES_REQUESTED** [review]
Changes looks good, works as expected. However, we probably should discuss my concern annotated in `JavaPsiClassWrapper`, that there could be more cases of non-testable classes.

Besides, having tests for those cases would be an extra gimmick :wink:

File: java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt (hunk 2 above)
Comment (stephanlukasczyk) [reply java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt:116]: From what I see, there is not reliable way to detect whether a file is part of the testing tree or not. Even searching the file path for something like `test` is just an heuristics, think of `it` for integration tests, for example.

The most reliable heuristics I can think of in the moment would be that we check for specific imports.  A file importing something from `org.junit.jupiter.api` would be a candidate for something test-related, because that is the JUnit 5 APIs for writing tests.  JUnit 4 makes it much harder because everything lives under `org.junit`, however, for example for implementations that use the runner APIs, we probably want to be able to generate tests.  Other candidates could be `com.google.guava` or `org.hamcrest` but this list will probably never be complete.

What do you think?

Comment (arksap2002) [reply java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt:116]: I like this idea actually, but which list of imports should I apply here? Only `org.junit.jupiter.api`, `com.google.guava` and `org.hamcrest`?

Comment (stephanlukasczyk) [reply java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt:116]: If I only had a definitive list 🙈 I'd say, `org.junit.jupiter.api`, `org.hamcrest`, `org.assertj`, and `com.google.common.truth`.  Note that in my previous comment I messed up Guava and Truth.  We want the latter, as a library for fluent assertions, which comes from `com.google.common.truth` packages.

Can you already extract the list from the function, such that it is easier to maintain?

File: java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt [hunk 4]
```diff
@@ -86,11 +92,37 @@ class JavaPsiClassWrapper(
...
+            return false
+        }
+
+        val importsSet =
+            fullText
+                .replace("\r\n", "\n")
+                .split("\n")
+                .asSequence()
+                .filter { it.contains("^import".toRegex()) }
+                .toMutableSet()
```
Comment (stephanlukasczyk) [inline java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt:119]: I'd prefer to not do this on the text of the file, with some string manipulations. Since we already have Psi at hand, why not using it, e.g.
```kotlin
val imports =
    (containingFile as PsiJavaFile) // this should always hold, since this class is for Java, shouldn't it?
        .importList
        ?.allImportStatements
        ?.map {
            (it as PsiImportStatement).qualifiedName
        }?.toImmutableSet()
```
Note that, depending on how you want to make the following check, replacing the `map` block's body with `it.text` might also be enough.

File: kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiClassWrapper.kt [hunk 5]
```diff
@@ -140,4 +140,39 @@ class KotlinPsiClassWrapper(
...
+        val importsSet =
+            fullText
+                .replace("\r\n", "\n")
+                .split("\n")
+                .asSequence()
+                .filter { it.contains("^import".toRegex()) }
+                .toMutableSet()
```
Comment (stephanlukasczyk) [inline kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiClassWrapper.kt:169]: Similar to my remark in `JavaPsiClassWrapper`, you better use Psi instead of string manipulations.

File: java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt [hunk 6]
```diff
@@ -86,11 +92,37 @@ class JavaPsiClassWrapper(
...
     }
 
-    /**
-     * Checks if the constraints on the selected class are satisfied, so that EvoSuite can generate tests for it.
-     * Namely, it is not an enum and not an anonymous inner class.
-     *
-     * @return true if the constraints are satisfied, false otherwise
-     */
-    fun isTestableClass(): Boolean = !psiClass.isEnum && psiClass !is PsiAnonymousClass
+    override fun getListOfTestingImports(): List<String> =
```
Comment (stephanlukasczyk) [inline java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt:95]: This function is duplicated to the one in `KotlinPsiClassWrapper`, couldn't we move it to the super class?

If there were specific imports only for Java or Kotlin, one can still override the function here.

**Review by stephanlukasczyk — CHANGES_REQUESTED** [review]
I had prefered if the changes to the test samples for the LLM had been a separate PR but hey, since that is basically just moving code around, I am happy to keep it here.

Please note my comments on the Psi part.

File: langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiClassWrapper.kt [hunk 7]
```diff
@@ -50,4 +50,24 @@ interface PsiClassWrapper {
...
+            "org.assertj",
+            "com.google.common.truth",
+        )
+
+    /**
+     * Determines if the class is testable based on specific criteria.
+     *
+     * @return true if the class is testable, false otherwise.
+     */
+    fun isValidTestClass(): Boolean
```
Comment (stephanlukasczyk) [inline langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiClassWrapper.kt:72]: Just thinking about this: isn't the name misleading? The function returns `true` if the class is testable, i.e., if it does not have any of the imports defined in `getListOfTestingImports`, am I correct?

If that's the case, I suggest renaming this function to `isValidSubjectUnderTest` and adjust the Javadoc accordingly, such that it tells the user what a valid SUT is, i.e., something in a file that does not import the aforementioned imports.

File: java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt [hunk 8]
```diff
@@ -86,11 +94,30 @@ class JavaPsiClassWrapper(
...
+        ) {
+            return false
+        }
+
+        val importsSet =
+            (containingFile as PsiJavaFile)
+                .importList
+                ?.allImportStatements
+                ?.map {
+                    (it as PsiImportStatement).qualifiedName
```
Comment (stephanlukasczyk) [inline java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt:112]: Sorry, need to come back to this, the cast fails 😔 

I attempted to right-click on a test class that has a `static` import. However, this will not be limited to test classes, it will probably hold for all classes with `static` imports.  What I get is the following `ClassCastException`:
```
java.lang.ClassCastException: class com.intellij.psi.impl.source.PsiImportStaticStatementImpl cannot be cast to class com.intellij.psi.PsiImportStatement (com.intellij.psi.impl.source.PsiImportStaticStatementImpl and com.intellij.psi.PsiImportStatement are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @1ec78798)
	at org.jetbrains.research.testspark.java.JavaPsiClassWrapper.isValidTestClass(JavaPsiClassWrapper.kt:112)
	at org.jetbrains.research.testspark.java.JavaPsiHelper.getSurroundingClass(JavaPsiHelper.kt:43)
	at org.jetbrains.research.testspark.langwrappers.PsiHelper.getCurrentListOfCodeTypes(PsiHelper.kt:158)
	at org.jetbrains.research.testspark.java.JavaPsiHelper.availableForGeneration(JavaPsiHelper.kt:33)
	at org.jetbrains.research.testspark.actions.TestSparkAction.update(TestSparkAction.kt:71)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate$lambda$2(ActionUtil.kt:226)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.kt:244)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$success$1$1$1.invoke(ActionUpdater.kt:501)
```
Changing this line to `it.text` seems to work, but please do me a favour and check with the various example programs you might have.

**Review by stephanlukasczyk — CHANGES_REQUESTED** [review]
Sorry, I have yet another set of changes, one about naming and one an actual but regarding `import static ...` statements

**Review by stephanlukasczyk — APPROVED** [review]
