### PR TITLE
[#231] PsiHelper refactoring

### LINKED ISSUE #231: Duplicated methods in PsiHelper and PromptManager
**Describe the bug**

```
 // Additional description of the method (grammar https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-4.3).
    var objectDescription: String = ""
 ```

Is I am not mistaken, this method is used inside EvoSuit to set up Settings Arguments, letting us properly start the EvoSuit test generation. In Llm we use it in PromtManager.kt in line  `val psiMethod = getPsiMethod(cut, codeType.objectDescription)!!`. Namely, to  retrieve a PsiMethod matching the given method descriptor within the provided PsiClass.

In the `promptManager` we already have `psiHelper` that is dedicated to work with Psi. Nevertheless, in `getPsiMethod` we generate `psiHelper` again to get the matching method, that we already have and can retrieve using caret and psiHelper. The same thing is with `getMethodDescriptor`

**Summary**

1) We have two methods (getPsiMethod, getMethodDescriptor) that duplicate the logic inside psiHelper.

- We should review the lines val psiMethod = getPsiMethod(cut, getMethodDescriptor(cut, lineNumber))!! and val psiMethod = getPsiMethod(cut, codeType.objectDescription)!! to determine if we can use the already existing psiHelper and caret to achieve the same functionality.

2) We can eliminate the use of generateMethodDescriptor inside llm.

*Reasoning*

Violation of DRY: The methods getPsiMethod and getMethodDescriptor replicate functionality that already exists in psiHelper. 

Violation of SRP: By consolidating the logic within psiHelper, the codebase will be more modular and easier to understand.

Code Efficiency: Reusing existing instances (psiHelper, caret) rather than generating new ones reduces unnecessary overhead and improves performance.

### PR DESCRIPTION
**Pull request by arksap2002**
# Description of changes made
Refactor the `PsiHelper` interface by
- removing copy paste between Kotlin and Java PsiHelpers.
- moving `getPsiMethod` and `getMethodDescriptor` the `PsiHelper`

# Other notes
Closes #231

- [x] I have checked that I am merging into correct branch

### CODE REVIEW

File: langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiHelper.kt [hunk 1]
```diff
@@ -0,0 +1,305 @@
...
+         */
+        val selectedLine = doc.getLineNumber(caretOffset)
+        val selectedLineText =
+            doc.getText(TextRange(doc.getLineStartOffset(selectedLine), doc.getLineEndOffset(selectedLine)))
+
+        if (selectedLineText.isBlank()) {
+            log.info("Line $selectedLine at caret $caretOffset is blank")
+            return null
+        }
+        log.info("Surrounding line at caret $caretOffset is $selectedLine")
```
Comment (stephanlukasczyk) [inline langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiHelper.kt:88]: If the `selectedLine` is 0-based but the actual lines in the code are 1-based, this (and the previous) log message might be misleading: having the cursor in line 42 results in `selectedLine = 41`, which is then logged, however, the user inspecting the log message then has to make the index shift. I therefore suggest to make the increment as soon as possible, i.e., after the `val selectedLineText = doc.getText(...)` line. Of course, this also needs an adjustment of the following `return` statement.

File: langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiHelper.kt [hunk 2]
```diff
@@ -0,0 +1,305 @@
...
+    /**
+     * Get the package name of the file.
+     */
+    abstract fun getPackageName(): String
+
+    /**
+     * Get the module of the file.
+     */
+    fun getModuleFromPsiFile(): com.intellij.openapi.module.Module =
+        ModuleUtilCore.findModuleForFile(psiFile.virtualFile, psiFile.project)!!
```
Comment (stephanlukasczyk) [inline langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiHelper.kt:271]: Might lead to `NullPointerException`s. It is probably better to return a `Module?` and let the caller check for the `null` value. That would require the client code to be aware of this, which avoids surprises.

**Review by stephanlukasczyk — CHANGES_REQUESTED** [review]
Thanks for the refactoring. One of my remarks (regarding the selected line number) is actually a nitpick, however, it could potentially lead to confusion. The other remark is regarding nullable return values: personally, I'd return a nullable value and let the client code deal with it instead of using the `!!` operator, which could lead to unexpected `NullPointerExceptions`.

**Review by stephanlukasczyk — APPROVED** [review]
LGTM
