### PR TITLE
Close generated tests tab, if all test were deleted

### LINKED ISSUE #330: Close generated tests tab, if all test were deleted
**Describe the bug**
If user will manually delete all tests, the tab have to be closed.

**Screenshots**
Screenshot 2024-08-29 at 4 48 35 PM

### PR DESCRIPTION
**Pull request by arksap2002**
# Description of changes made
If user will manually delete all tests, the tab have to be closed.

# Other notes
Closes #330 
- [x] I have checked that I am merging into correct branch

### CODE REVIEW

**Review by pderakhshanfar — APPROVED** [review]

File: src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TopButtonsPanelBuilder.kt [hunk 1]
```diff
@@ -41,13 +41,21 @@ class TopButtonsPanelBuilder {
...
+            if (testCasePanelFactory.isRemoved()) {
+                numberOfRemovedTests++
+                continue
+            }
             val error = testCasePanelFactory.getError()
             if ((error is String) && error.isEmpty()) {
                 numberOfPassedTests++
             }
         }
+        if (generatedTestsTabData.testCasePanelFactories.size == numberOfRemovedTests) {
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TopButtonsPanelBuilder.kt:55]: The code will be easier to read if we use stream API here:
```kotlin
// ATTENTION: I did not test these expressions; only re-wrote the existing code
val passedTestsCount = generatedTestsTabData.testCasePanelFactories
            .filter { !it.isRemoved() }
            .count { it.getError()?.isEmpty() == true }
            
val removedTestsCount = generatedTestsTabData.testCasePanelFactories.count { it.isRemoved() }
``` 
Working with immutable variables makes coding reading easier here.

**Review by Vladislav0Art — CHANGES_REQUESTED** [review]

**Review by Vladislav0Art — APPROVED** [review]
