### PR TITLE
Fix Issue 390: Better generation process monitor

### LINKED ISSUE #390: "Generation is already running" warning when a different project opened
**Describe the bug**
I ran TestSpark on a project A and received a test suite in the sidebar (I did not delete the sidebar). I closed the current project via pressing 'X' button on a mac window (notice that I did not close the IDE but a project within the same IDE instance!). I opened a different project and received the following warning:

Screenshot 2024-10-11 at 16 28 26

This warning neither allows me to execute any subsequent generations nor does it terminate the previous generation if I click "Terminate". It is sort of **soft deadlock**. I can only re-open the IDE to fix this.

**To Reproduce**
1. Open a project A;
2. Generate tests and do not close the sidebar (idk whether it matters);
3. Close the project A;
4. Open a project B (A != B);
5. Attempt to generate tests in project B -> warning occurred -> try to terminate -> no-op -> soft deadlock.

**Expected behavior**
No soft deadlocks.

### PR DESCRIPTION
**Pull request by pderakhshanfar**
# Description of changes made
This PR fixes #390 issue and provides a better process monitoring procedure

# Why is merge request needed
Fixes #390 

# What is missing?
We need a major refactoring by removing controller totally and using indicator instead to track the status of test generation processes

- [x] I have checked that I am merging into correct branch

### CODE REVIEW

File: src/main/kotlin/org/jetbrains/research/testspark/actions/controllers/TestGenerationController.kt [hunk 1]
```diff
@@ -26,6 +27,7 @@ class TestGenerationController {
     private fun showGenerationRunningNotification(project: Project) {
         val terminateButton: AnAction = object : AnAction("Terminate") {
             override fun actionPerformed(e: AnActionEvent) {
+                indicator?.stop()
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/actions/controllers/TestGenerationController.kt:30]: It would be nice to close this popup modal after a user clicks "Terminate." Otherwise, I can click as many times as I like (it does not cause errors, though).

**Review by Vladislav0Art — APPROVED** [review]
I left some suggestions about small code parts.

Generally, my main concern is using `CustomProgressIndicator` even further in the plugin's control flow.
